/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "Port/Std/IfxPort.h"
#include "Bsp.h"
#include "App/Hardware/Led.h"

IFX_ALIGN(4)
IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);




    // 板子设计按键上拉 , 低电平按下
    #define KEY_0_PORT &MODULE_P20
    #define KEY_0_PIN 6
    #define KEY_1_PORT &MODULE_P20
    #define KEY_1_PIN 7
    #define KEY_2_PORT &MODULE_P11
    #define KEY_2_PIN 2
    #define KEY_3_PORT &MODULE_P11
    #define KEY_3_PIN 3
    // 设置为 上拉输入
    IfxPort_setPinModeInput(KEY_0_PORT, KEY_0_PIN, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(KEY_1_PORT, KEY_1_PIN, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(KEY_2_PORT, KEY_2_PIN, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(KEY_3_PORT, KEY_3_PIN, IfxPort_InputMode_pullUp);
    // 配置输入 Pad
    IfxPort_setPinPadDriver(KEY_0_PORT, KEY_0_PIN, IfxPort_PadDriver_cmosAutomotiveSpeed4);
    IfxPort_setPinPadDriver(KEY_1_PORT, KEY_1_PIN, IfxPort_PadDriver_cmosAutomotiveSpeed4);
    IfxPort_setPinPadDriver(KEY_2_PORT, KEY_2_PIN, IfxPort_PadDriver_cmosAutomotiveSpeed4);
    IfxPort_setPinPadDriver(KEY_3_PORT, KEY_3_PIN, IfxPort_PadDriver_cmosAutomotiveSpeed4);

    Led_Init();
    while (1)
    {
        if(IfxPort_getPinState(KEY_0_PORT, KEY_0_PIN) == 0)
        {
            Led_On(LED_0);
        }
        else
        {
            Led_Off(LED_0);
            
        }
        if(IfxPort_getPinState(KEY_1_PORT, KEY_1_PIN) == 0)
        {
            Led_On(LED_1);
        }
        else
        {
            Led_Off(LED_1);
        }
         if(IfxPort_getPinState(KEY_2_PORT, KEY_2_PIN) == 0)
        {
            Led_On(LED_2);
        }
        else
        {
            Led_Off(LED_2);
            
        }
        if(IfxPort_getPinState(KEY_3_PORT, KEY_3_PIN) == 0)
        {
            Led_On(LED_3);
        }
        else
        {
            Led_Off(LED_3);
        }       


    }
}
