/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "Port/Std/IfxPort.h"
#include "Bsp.h"
#include "App/Hardware/Led.h"
#include "App/Hardware/Key.h"

IFX_ALIGN(4)
IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);




    // 板子设计按键上拉 , 低电平按下
    // 按键与 LED 的引脚、按下极性等板级配置已封装进 App/Hardware/Key.h 的表驱动
    // 这里只做一次初始化, 由 Key_Init() 按表逐键配置输入模式与 Pad 特性

    Led_Init();
    Key_Init();
    while (1)
    {
        // 按下第几个按键就点亮第几个灯: 轮询 Key_IsPressed(), 按下亮、松开灭
        if(Key_IsPressed(KEY_0))
        {
            Led_On(LED_0);
        }
        else
        {
            Led_Off(LED_0);
        }
        if(Key_IsPressed(KEY_1))
        {
            Led_On(LED_1);
        }
        else
        {
            Led_Off(LED_1);
        }
         if(Key_IsPressed(KEY_2))
        {
            Led_On(LED_2);
        }
        else
        {
            Led_Off(LED_2);
        }
        if(Key_IsPressed(KEY_3))
        {
            Led_On(LED_3);
        }
        else
        {
            Led_Off(LED_3);
        }
    }
}
