/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "Port/Std/IfxPort.h"
#include "Bsp.h"
#include "App/Hardware/Led.h"
#include "App/Hardware/Key.h"
#include "IfxStm_Timer.h"


IFX_ALIGN(4)
IfxCpu_syncEvent g_cpuSyncEvent = 0;


// 定时器中断优先级 = 2
#define ISR_PRIORITY_TIMER_1000MS (2)
// 中断服务提供者 = CPU0
#define ISR_PROVIDER_TIMER_1000MS IfxSrc_Tos_cpu0

IfxStm_Timer myTimer;   // 定义一个 STM 定时器驱动对象

boolean AppInit_1000ms(void)
{
    boolean result = TRUE;
    IfxStm_Timer_Config timerConfig;           // 配置结构体
    IfxStm_Timer_initConfig(&timerConfig, &MODULE_STM0);   // 拿默认配置（基于 STM0）
    timerConfig.base.frequency     = 1;     // 中断频率 = 1Hz（即 1000ms 一次）
    timerConfig.base.isrPriority   = ISR_PRIORITY_TIMER_1000MS;   // 中断优先级
    timerConfig.base.isrProvider   = ISR_PROVIDER_TIMER_1000MS;   // 中断目标 CPU
    timerConfig.base.minResolution = (1.0f / timerConfig.base.frequency) / 1000;  // 最小分辨率
    timerConfig.comparator         = IfxStm_Comparator_0;  // 用比较器 0
    result = IfxStm_Timer_init(&myTimer, &timerConfig);    // 真正初始化
    IfxStm_Timer_run(&myTimer);   // 启动定时器
    return result;
}

// 中断服务函数：IFX_INTERRUPT(函数名, 保留位, 优先级)
IFX_INTERRUPT(ISR_TIMER_1000ms, 0, ISR_PRIORITY_TIMER_1000MS)
{
    __enable();                    // 重新使能中断（允许嵌套/继续响应）
    IfxStm_Timer_acknowledgeTimerIrq(&myTimer);   // ★关键：清中断标志 + 设置下一次比较值
    Led_Toggle(LED_0);   // 每次中断切换 LED0
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    Led_Init();
    Key_Init();
    AppInit_1000ms();


    while (1)
    {

    }
}
